device:
  type: "cpu"

data:
  num_samples   : 1024
  num_neurons   : 500
  num_words     : 100
  num_timesteps : 300

training:
  batch_size  : 32
  num_workers : 0
  pin_memory  : True
  z_dim       : 128

vae_model:
  name       : "model_vae"

  input_dim  : 150000
  hidden_dim : 1024
  latent_dim : 128

  num_epochs : 20
  beta_loss  : 1.0
  lr         : 0.0001

paths:
  output_path: "experiment_outputs"